old_lessons/django_test/lms/urls.py
from core.views import index

import debug_toolbar

from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static

from lms import settings

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),

    path('admin/', admin.site.urls),

    path('', index, name='index'),

    path('students/', include('students.urls')),

    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),

    path('courses/', include('courses.urls')),

    path('accounts/', include('accounts.urls')),

    path('accounts/', include('django.contrib.auth.urls'))


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

old_lessons/django_test/teachers/urls.py
from django.urls import path
from teachers.forms import TeacherCreateForm

from teachers.views import TeacherListView, CreateTeacherView, TeacherUpdateView, delete_teacher


app_name = 'teachers'

urlpatterns = [
    path('', TeacherListView.as_view(), name='list'),
    path('create/', CreateTeacherView.as_view(), name='create'),
    path('update/<int:pk>/', TeacherUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', delete_teacher, name='delete'),
]

old_lessons/django_test/teachers/models.py
from django.db import models
from django.db.models.deletion import SET_NULL

from faker import Faker
from courses.models import Course

from core.models import Person, get_obj

from random import randint


class Teacher(Person):
    salary = models.PositiveIntegerField(default=1500)

    subject = models.CharField(max_length=100, null=False)
    specialization = models.CharField(max_length=100)

    @classmethod
    def _generate(cls):
        fake = Faker()
        obj = super()._generate()
        obj.salary = randint(500, 3000)
        obj.specialization=fake.job(),
        obj.subject=get_obj(Course),
        obj.save()
        # print (get_obj(Course))


# Generating fake data (Teacher's objects)
# Teacher.generate(10)

old_lessons/django_test/teachers/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

import django_filters

from teachers.models import Teacher


class TeacherCreateForm(ModelForm):
    class Meta:
        model = Teacher
        fields = [
            'last_name', 
            'first_name', 
            'subject', 
            'specialization'
            ]


class TeacherUpdateForm(TeacherCreateForm):
    class Meta(TeacherCreateForm.Meta):
        fields = [
            "last_name",
            "first_name",
            "subject",
            "specialization",
        ]


class TeacherFilter(django_filters.FilterSet):
    class Meta:
        model = Teacher
        fields = {
            'subject': ['exact', 'icontains'],
            'first_name': ['exact', 'icontains'],
            'last_name': ['exact', 'icontains'],
        }

old_lessons/django_test/teachers/views.py
from typing import Reversible
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls.base import reverse, reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView, DeleteView

from teachers.forms import TeacherCreateForm, TeacherUpdateForm, TeacherFilter
from teachers.models import Teacher

from webargs import fields
from webargs.djangoparser import use_args


class TeacherListView(ListView):
    model = Teacher
    template_name = 'teachers/list.html'
    paginate_by = 10


    def get_filter(self):
        return TeacherFilter(
            data=self.request.GET,
            queryset=self.model.objects.all()
        )

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_filter'] = self.get_filter()

        return context


class CreateTeacherView(CreateView):
    model = Teacher
    form_class = TeacherCreateForm
    success_url = reverse_lazy('teachers:list')
    template_name = 'teachers/create.html'


class TeacherUpdateView(UpdateView):
    model = Teacher
    form_class = TeacherUpdateForm
    success_url = reverse_lazy('teachers:list')
    template_name = 'teachers/update.html'


class TeacherDeleteView(DeleteView):
    model = Teacher
    template_name = 'teachers/delete.html'
    success_url = reverse_lazy('teachers:list')



def delete_teacher(request, pk):
    teacher = get_object_or_404(Teacher, id=pk)
    if request.method == 'POST':
        teacher.delete()
        return HttpResponseRedirect(reverse('teachers:list'))

    return render(
        request=request,
        template_name='teachers/delete.html',
        context={
            'teacher': Teacher
        }
    )

old_lessons/django_test/teachers/templates/teachers/create.html
{%extends 'base.html' %}

{% load crispy_forms_tags %}

{%block title%}
    <title>Create teacher</title>
{%endblock%}

{%block page_name%}
  <h1>Create teacher</h1>
{%endblock%}


{%block content%}

  <form method="post">
    {% csrf_token %}
    {{form | crispy }}
    <input type="submit" value="Create">
  </form>

  <a href="{% url 'teachers:list' %}">Back to Teachers list</a><br>

{%endblock%}

old_lessons/django_test/teachers/templates/teachers/delete.html
{%extends 'base.html' %}

{% block title %}
    <title>Delete teacher</title>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Do you want to delete? {{ teacher.last_name}} {{ teacher.first_name}}</p>
        <input class="btn btn-danger" type="submit" value="Agree">
        <a class="btn btn-primary" href="{% url 'teachers:list'%}"> Cancel </a>
    </form>
{% endblock %}s

old_lessons/django_test/teachers/templates/teachers/list.html
{%extends 'base.html' %}

{% load crispy_forms_tags %}

{%block title%}
    <title>Teachers list</title>
{%endblock%}

{%block page_name%}
    <h1>Teachers List</h1>
{%endblock%}

{%block content%}

<form method="get">

    {{ obj_filter.form | crispy }}

    <input class="btn btn-success mb-3 mt-3" type="submit" value="Search">
</form>


<a href="{% url 'teachers:create' %}">Create teacher</a><br>


    <table class="table table-success table-striped">
        <tr>
        <td>First Name</td>
        <td>Last Name</td>
        <td>Specialization</td>
        <td>Group</td>
        <td>Edit</td>
        <td>Delete</td>
        </tr>
    
        {% for teacher in object_list %}
            <tr>
                <th>{{teacher.first_name}}</th>
                <th>{{teacher.last_name}}</th>
                <th>{{teacher.specialization}}</th>
                <th> {%for group in groups.teacher.all%}
                    
                    {{group.group_name}} </br> 
                     
                    {%endfor%} </th>
                <th> <a href="{% url 'teachers:update' teacher.pk %}"> EDIT</a> </th>
                <th> <a href="{% url 'teachers:delete' teacher.pk %}"> DELETE</a> </th>
            </tr>
        {% endfor %}
        </table>

        {%include 'includes/paginator.html' %} 


{%endblock%}

old_lessons/django_test/teachers/templates/teachers/update.html
{%extends 'base.html' %}

{% load crispy_forms_tags %}

{%block title%}
    <title>Update teacher</title>
{%endblock%}

{%block page_name%}
    <h1>Update teacher</h1>
{%endblock%}


{%block content%}

    <form method="post">
        {% csrf_token %}
        {{form | crispy}}
        <input type="submit" value="Update">
    </form>

    <a href="{% url 'teachers:list' %}">Back to Teachers list</a><br>

{%endblock%}