old_lessons/django_test/groups/urls.py
from groups.views import GroupListView, GroupUpdateView, CreateGroupView, delete_Group
from django.urls import path

#  from .views import GroupUpdateView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', CreateGroupView.as_view(), name='create'),
    path('update/<int:pk>/', GroupUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', delete_Group, name='delete'),
]

old_lessons/django_test/lms/urls.py
from core.views import index

import debug_toolbar

from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static

from lms import settings

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),

    path('admin/', admin.site.urls),

    path('', index, name='index'),

    path('students/', include('students.urls')),

    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),

    path('courses/', include('courses.urls')),

    path('accounts/', include('accounts.urls')),

    path('accounts/', include('django.contrib.auth.urls'))


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

old_lessons/django_test/students/urls.py
from django.urls import path

from .views import CreateStudentView, StudentDeleteView, StudentListView, StudentUpdateView

app_name = 'students'

urlpatterns = [
    # path('', get_students, name='list'),
    # path('create/', create_student, name='create'),
    # path('update/<int:id>/', update_student, name='update'),
    # path('update/<int:pk>/', UpdateStudentView.update_object, name='update'),

    path ('', StudentListView.as_view(), name='list'),
    path ('create/', CreateStudentView.as_view(), name='create'),
    path('update/<int:pk>/', StudentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', StudentDeleteView.as_view(), name='delete'),
]

old_lessons/django_test/groups/models.py
import datetime
import random

from django.db import models

# Create your models here.
from faker import Faker
from core.models import get_obj

from teachers.models import Teacher
from courses.models import Course

class Group(models.Model):

    group_name = models.CharField(max_length=100)
    creation_date = models.DateField(null=False, default=datetime.date.today)
    subject = models.CharField(max_length=100, null=False)

    headman = models.OneToOneField(
        'students.Students',
        on_delete=models.SET_NULL,
        null=True,
        related_name='headed_group'
    )

    teachers = models.ManyToManyField(
        to=Teacher,
        related_name='groups'
    )    

    def __str__(self):
        return f'{self.id}, {self.group_name}, {self.subject}, {self.creation_date}'

    @staticmethod
    def generate_groups(count):
        faker = Faker()
        for _ in range(count):
            st = Group(
                group_name=faker.catch_phrase(),
                creation_date=faker.date_between(start_date='-5y', end_date='-1y'),
                subject=str(get_obj(Course).subject)
            )
            st.save()

old_lessons/django_test/groups/forms.py
from django.forms import ModelForm

import django_filters

from groups.models import Group


class GroupCreateForm(ModelForm):
    class Meta:
        model = Group
        fields = ['group_name', 'subject', 'creation_date']


class GroupUpdateForm(GroupCreateForm):
    class Meta(GroupCreateForm.Meta):
        fields = [
            'group_name',
            'subject',
            'creation_date',
            'headman',
            'teachers'
        ]


class GroupFilter(django_filters.FilterSet):
    class Meta:
        model = Group
        fields = {
            'subject': ['exact','icontains'],
            'group_name': ['exact', 'icontains'],
        }

old_lessons/django_test/groups/views.py
from typing import Reversible
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls.base import reverse, reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView, DeleteView

from groups.forms import GroupCreateForm, GroupUpdateForm, GroupFilter
from groups.models import Group

from webargs import fields
from webargs.djangoparser import use_args

from students.models import Students


class GroupListView(LoginRequiredMixin, ListView):
    model = Group
    template_name = 'groups/list.html'
    paginate_by = 3

    def get_filter(self):
        return GroupFilter(
            data=self.request.GET,
            queryset=self.model.objects.all()
        )

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_filter'] = self.get_filter()

        return context
 


class CreateGroupView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupCreateForm
    success_url = reverse_lazy('groups:list')
    template_name = 'groups/create.html'

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f'Group {form.cleaned_data["group_name"]} been created.')

        return result


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = Group
    form_class = GroupUpdateForm
    success_url = reverse_lazy('groups:list')
    template_name = 'groups/update.html'

    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['students'] = self.get_object().students.select_related('group', 'headed_group').all()

        return context

    def get_initial(self):
        initial = super().get_initial()
        try:
            initial['headman_field'] = self.object.headman.id
        except AttributeError as ex:
            pass

        return initial

    def form_valid(self, form):
        respose = super().form_valid(form)
        form.instance.headman = Students.objects.get(id=form.cleaned_data['headman_field'])
        form.instance.save()

        return respose



def delete_Group(request, pk):
    group = get_object_or_404(Group, id=pk)
    if request.method == 'POST':
        group.delete()
        return HttpResponseRedirect(reverse('groups:list'))

    return render(
        request=request,
        template_name='groups/delete.html',
        context={
            'groups': Group
        }
    )

class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    template_name = 'groups/delete.html'
    success_url = reverse_lazy('groups:list')

old_lessons/django_test/groups/templates/groups/create.html
{%extends 'base.html' %}

{% load crispy_forms_tags %}

{%block title%}
    <title>Create group</title>
{%endblock%}

{%block page_name%}
  <h1>Create group</h1>
{%endblock%}


{%block content%}  

  <form method="post">
    {% csrf_token %}
    {{form | crispy}}
    <input type="submit" value="Create">
  </form>

  <a href="{% url 'groups:list' %}">Back to Group list</a><br>

{%endblock%}

old_lessons/django_test/groups/templates/groups/custom.html
{% extends 'admin/change_form.html' %}

old_lessons/django_test/groups/templates/groups/delete.html
{%extends 'base.html' %}

{% block title %}
    <title>Delete group</title>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Do you want to delete? {{group.group_name}}</p>
        <input class="btn btn-danger" type="submit" value="Agree">
        <a class="btn btn-primary" href="{% url 'groups:list'%}"> Cancel </a>
    </form>
{% endblock %}s

old_lessons/django_test/groups/templates/groups/list.html
{%extends 'base.html' %}

{% load crispy_forms_tags %}

{%block title%}
<title>Groups list</title>
{%endblock%}

{%block page_name%}
    <h1>Group List</h1>
{%endblock%}


{%block content%}
    
    <form method="get">

        {{ obj_filter.form | crispy }}
    
        <input class="btn btn-success mb-3 mt-3" type="submit" value="Search">
    </form>
    
    <a href="{% url 'groups:create' %}">Create group</a><br>

    <table class="table table-hover">
        <tr>
        <td>Group Name</td>
        <td>Subject</td>
        <td>Creation date</td>
        <td>Group headman</td> 
        <td>Teachers in group</td>       
      
        <td>Edit</td>
        <td>Delete</td>
        </tr>
    
        {% for group in object_list %}
            <tr>
                <th>{{group.group_name}}</th>
                <th>{{group.subject}}</th>
                <th>{{group.creation_date}}</th>
                <th>{{group.headman}}</th>
                <th> {%for teacher in group.teachers.all%}
                    
                    {{teacher.last_name}} {{teacher.first_name}} </br> 
                    
        {%endfor%} </th>
        
            <th> <a href="{% url 'groups:update' group.id %}">EDIT</a> </th>
        
            <th> <a href="{% url 'groups:delete' group.pk %}">Delete</a> </th>
    
            </tr>
        {% endfor %}
        </table> 
    
        {%include 'includes/paginator.html' %} 


{%endblock%}

old_lessons/django_test/groups/templates/groups/update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Update_group
{% endblock %}

{% block header %}
    Update group
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn btn-success mt-3" type="submit" id="btn_save">Save</button>
        <a class="btn btn-primary mt-3" href="{% url 'groups:list' %}">Cancel</a>
    </form>
{#  {% with list_objects=group.students.all %} #}
    {% with list_objects=students %}
        {% include 'includes/students_list_table.html' %}
    {% endwith %}
{#    <table class="table table-hover table-sm">#}
{#        <tr>#}
{#            <th></th>#}
{#            <th>First name</th>#}
{#            <th>Last name</th>#}
{#            <th>Email</th>#}
{#            <th>age</th>#}
{#            <th><i class="bi bi-pencil-fill"></i></th>#}
{#            <th>🚮</th>#}
{#        </tr>#}
{#        {% for student in group.students.all %}#}
{#        <tr>#}
{#            <td>{{ forloop.counter }}</td>#}
{#            <td>{{ student.first_name }}</td>#}
{#            <td>{{ student.last_name }}</td>#}
{#            <td>{{ student.email }}</td>#}
{#            <td>{{ student.age }}</td>#}
{#            <td><a href="{% url 'students:update' student.id %}">EDIT</a></td>#}
{#            <td><a href="{% url 'students:delete' student.id %}">DELETE</a></td>#}
{#        </tr>#}
{#        {% endfor %}#}
{#    </table>#}
{% endblock %}