old_lessons/django_test/accounts/urls.py
from django.contrib.auth import views
from django.urls import path
from django.urls.base import reverse_lazy
from django.views.generic.base import View

from .views import AccountPasswordChange, AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView

app_name = 'accounts'

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('change_password/', AccountPasswordChange.as_view(), name='change_password'),
    path('profile_update/', AccountUpdateView.as_view(), name='profile_update'),


    path(
        'password-reset/', 
        views.PasswordResetView.as_view(
            template_name='accounts/password_reset_form.html',
            success_url=reverse_lazy('accounts:password_reset_done')
            ),
        name='password_reset'
        ),


    path(
        'password-reset-confirm/<uidb64>/<token>/', 
        views.PasswordResetConfirmView.as_view(
            template_name='accounts/password_reset_confirm.html'
            ),
        name='password_reset_confirm'
        ),


    path(
        'password-reset-done/', 
        views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html',
            ),
        name='password_reset_done'
        ),

    
    


]

old_lessons/django_test/groups/urls.py
from groups.views import GroupListView, GroupUpdateView, CreateGroupView, delete_Group
from django.urls import path

#  from .views import GroupUpdateView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', CreateGroupView.as_view(), name='create'),
    path('update/<int:pk>/', GroupUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', delete_Group, name='delete'),
]

old_lessons/django_test/lms/urls.py
from core.views import index

import debug_toolbar

from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static

from lms import settings

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),

    path('admin/', admin.site.urls),

    path('', index, name='index'),

    path('students/', include('students.urls')),

    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),

    path('courses/', include('courses.urls')),

    path('accounts/', include('accounts.urls')),

    path('accounts/', include('django.contrib.auth.urls'))


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

old_lessons/django_test/students/urls.py
from django.urls import path

from .views import CreateStudentView, StudentDeleteView, StudentListView, StudentUpdateView

app_name = 'students'

urlpatterns = [
    # path('', get_students, name='list'),
    # path('create/', create_student, name='create'),
    # path('update/<int:id>/', update_student, name='update'),
    # path('update/<int:pk>/', UpdateStudentView.update_object, name='update'),

    path ('', StudentListView.as_view(), name='list'),
    path ('create/', CreateStudentView.as_view(), name='create'),
    path('update/<int:pk>/', StudentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', StudentDeleteView.as_view(), name='delete'),
]

old_lessons/django_test/teachers/urls.py
from django.urls import path
from teachers.forms import TeacherCreateForm

from teachers.views import TeacherListView, CreateTeacherView, TeacherUpdateView, delete_teacher


app_name = 'teachers'

urlpatterns = [
    path('', TeacherListView.as_view(), name='list'),
    path('create/', CreateTeacherView.as_view(), name='create'),
    path('update/<int:pk>/', TeacherUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', delete_teacher, name='delete'),
]

old_lessons/django_test/templates/includes/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

old_lessons/django_test/templates/includes/nav_bar.html
<nav class="navbar navbar-light fixed-top navbar-expand-lg font-weight-bold" style="background-color: #e3f2fd;">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">LMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Students
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'students:list' %}">List of students</a></li>
            <li><a class="dropdown-item" href="{% url 'students:create' %}">Create new student</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Groups
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'groups:list' %}">List of groups</a></li>
            <li><a class="dropdown-item" href="{% url 'groups:create' %}">Create new group</a></li>
          </ul>
        </li>



        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Teachers
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'teachers:list' %}">List of teachers</a></li>
            <li><a class="dropdown-item" href="{% url 'teachers:create' %}">Create new teacher</a></li>
          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link " href="/about">About us</a>
        </li>

      <form class="d-flex me-center">
        <a class="btn btn-outline-success" data-bs-toggle="collapse" href="#collapseExample" role="button"
           aria-expanded="false" aria-controls="collapseExample">
            Search
        </a>
      </form>




    </ul>
    <ul class="navbar-nav">

       <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle p-1 m-1" href="#" id="navbarDropdown3" role="button" data-bs-toggle="dropdown" aria-expanded="false">

        {% if user.is_authenticated %}
          <img class="rounded-circle p-1 m-1" width="40" height="40" src="{{ user.profile.avatar.url }}" text="name">{{user.username}}

        {% else %}
          <img class="rounded-circle p-1 m-1" width="40" height="40" src="/media/avatars/avatar.jpg" >Anonymous

         {% endif %}
        </a>



         <ul class="dropdown-menu" aria-labelledby="navbarDropdown3">
         {% if user.is_authenticated %}
             <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Sign Out</a></li>
             <li><hr class="dropdown-divider"></li>
             <li><a class="dropdown-item" href="{% url 'accounts:profile_update' %}">Profile {{ user.username }}</a></li>
             <li><hr class="dropdown-divider"></li>
             <li><a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change password</a></li>
             <li><hr class="dropdown-divider"></li>
             <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password other</a></li>

         {% else %}
           <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Sign In</a></li>
           <li><hr class="dropdown-divider"></li>
           <li><a class="dropdown-item" href="{% url 'accounts:password_reset' %}">Reset Password</a></li>
           <li><hr class="dropdown-divider"></li>
           <li><a class="dropdown-item" href="{% url 'accounts:registration' %}">Registration</a></li>
         {% endif %}
         </ul>
       </li>
     </ul>    

    </div>
  </div>
</nav>

old_lessons/django_test/templates/includes/paginator.html
<nav aria-label="Page navigation example">
  <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1&{{ get_params }}">&laquo; First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ get_params }}">Previous</a></li>
      {% endif %}

      {% for page_num in page_obj.paginator.page_range %}
        {% if page_num == page_obj.number %}
            <li class="page-item active"><a class="page-link" href="?page={{ page_num }}&{{ get_params }}">{{ page_num }}</a></li>
        {% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}
            <li class="page-item"><a class="page-link" href="?page={{ page_num }}&{{ get_params }}">{{ page_num }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ get_params }}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&{{ get_params }}">Last &raquo;</a></li>
      {% endif %}

  </ul>
</nav>

old_lessons/django_test/templates/includes/students_list_table.html
<table class="table table-hover table-sm">
    <tr>
        <th>ID</th> 
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Age</th>
        <th>Group</th>
        <th>Head man</th>
        <th><i class="bi bi-pencil-fill"></i></th>
        <th>🚮</th>
    </tr>
    {% for student in list_objects %}
        <tr>
            <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
            <td>{{ student.first_name }}</td>
            <td>{{ student.last_name }}</td>
            <td>{{ student.email }}</td>
            <td>{{ student.age }}</td>
            <td>{% if student.group %}{{ student.group }}{% endif %}</td>
            <td>{% if student.headed_group %}{{ student.headed_group }}{% endif %}</td>
            <td><a href="{% url 'students:update' student.id %}">EDIT</a></td>
            <td><a href="{% url 'students:delete' student.id %}">DELETE</a></td>
        </tr>
    {% endfor %}
</table>