old_lessons/django_test/courses/urls.py
from courses.views import CourseListView, CreateCourseView, CourseUpdateView, delete_Course

from django.urls import path

app_name = 'courses'

urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('create/', CreateCourseView.as_view(), name='create'),
    path('update/<int:pk>/', CourseUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', delete_Course, name='delete'),
]

old_lessons/django_test/groups/urls.py
from groups.views import GroupListView, GroupUpdateView, CreateGroupView, delete_Group
from django.urls import path

#  from .views import GroupUpdateView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('create/', CreateGroupView.as_view(), name='create'),
    path('update/<int:pk>/', GroupUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', delete_Group, name='delete'),
]

old_lessons/django_test/lms/urls.py
from core.views import index

import debug_toolbar

from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static

from lms import settings

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),

    path('admin/', admin.site.urls),

    path('', index, name='index'),

    path('students/', include('students.urls')),

    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),

    path('courses/', include('courses.urls')),

    path('accounts/', include('accounts.urls')),

    path('accounts/', include('django.contrib.auth.urls'))


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

old_lessons/django_test/students/urls.py
from django.urls import path

from .views import CreateStudentView, StudentDeleteView, StudentListView, StudentUpdateView

app_name = 'students'

urlpatterns = [
    # path('', get_students, name='list'),
    # path('create/', create_student, name='create'),
    # path('update/<int:id>/', update_student, name='update'),
    # path('update/<int:pk>/', UpdateStudentView.update_object, name='update'),

    path ('', StudentListView.as_view(), name='list'),
    path ('create/', CreateStudentView.as_view(), name='create'),
    path('update/<int:pk>/', StudentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', StudentDeleteView.as_view(), name='delete'),
]

old_lessons/django_test/teachers/urls.py
from django.urls import path
from teachers.forms import TeacherCreateForm

from teachers.views import TeacherListView, CreateTeacherView, TeacherUpdateView, delete_teacher


app_name = 'teachers'

urlpatterns = [
    path('', TeacherListView.as_view(), name='list'),
    path('create/', CreateTeacherView.as_view(), name='create'),
    path('update/<int:pk>/', TeacherUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', delete_teacher, name='delete'),
]

old_lessons/django_test/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LMS -
        {% block title%}
            Home
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <style>{% block custom_css %}{% endblock %}</style>
</head>
<body>
  {% include 'includes/nav_bar.html' %}

  <div class="container mt-4 pt-4">
    <div class="border rounded text-center p-3 m-3 mb-5 bg-light shadow">
        <h1>{% block header %}Welcome to LMS!!!{% endblock %}</h1>
    </div>
    {% include 'includes/messages.html' %}
    {% block content %}{% endblock %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
          crossorigin="anonymous"></script>
</body>
</html>

old_lessons/django_test/templates/flatpage.html
{%extends 'base.html' %}

{%block title%} {{flatpage.title}}} {%endblock%}

{%block content%}

<h1>Hello</h1>

{%endblock%}

old_lessons/django_test/templates/index.html
{%extends 'base.html' %}

{%block content%}
      <div class="list-group">
        <a href="{%url 'students:list'%}"> Students list </a>         
        <a href="{%url 'groups:list'%}"> Groups list </a>
        <a href="{%url 'teachers:list'%}"> Teachers list </a>
        <a href="{%url 'courses:list'%}"> Course list </a>

      </div>

{%endblock%}